=== rajvseetharaman/Player_Base/XMLandXSD/playerBase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cricketPlayerBase">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="about">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="title"/>
                            <xs:element name="author"/>
                            <xs:element ref="description"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cricketPlayers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cricketPlayer" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="title"/>
                                        <xs:element ref="description"/>
                                        <xs:element name="photos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="photo">
                                                  <xs:complexType>
                                                  <xs:attribute ref="id"/>
                                                  <xs:attribute name="fileName" type="xs:anyURI"/>
                                                  <xs:attribute name="caption"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="age"/>
                                        <xs:element name="gender">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:enumeration value="Male"/>
                                                  <xs:enumeration value="Female"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="nationalSide">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:enumeration value="India"/>
                                                  <xs:enumeration value="England"/>
                                                  <xs:enumeration value="Australia"/>
                                                  <xs:enumeration value="Bangladesh"/>
                                                  <xs:enumeration value="New Zealand"/>
                                                  <xs:enumeration value="Pakistan"/>
                                                  <xs:enumeration value="South Africa"/>
                                                  <xs:enumeration value="Sri Lanka"/>
                                                  <xs:enumeration value="West Indies"/>
                                                  <xs:enumeration value="Canada"/>
                                                  <xs:enumeration value="Ireland"/>
                                                  <xs:enumeration value="Kenya"/>
                                                  <xs:enumeration value="USA"/>
                                                  <xs:enumeration value="UAE"/>
                                                  <xs:enumeration value="Afghanistan"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="teamsPlayedFor">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="team" maxOccurs="unbounded">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="teamName"/>
                                                  </xs:sequence>
                                                  <xs:attribute ref="id"/>
                                                  <xs:attribute name="league"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="playingRole"/>
                                        <xs:element name="battingStyle">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:enumeration value="Right Handed"/>
                                                  <xs:enumeration value="Left Handed"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="bowlingStyle"/>
                                        <xs:element name="gameStats">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="matchesPlayed"/>
                                                  <xs:element name="inningsPlayed"/>
                                                  <xs:element name="battingAverages">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="runs"/>
                                                  <xs:element name="centuries"/>
                                                  <xs:element name="halfCenturies"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="bowlingAverages">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="wickets"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                  <xs:element name="fieldingAverages">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element name="catches"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="sources">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded"
                                                  name="sourceRefId" type="xs:IDREF"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="relatedPlayers">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded"
                                                  ref="playerRefId"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute ref="id" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="sources">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="source">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name"/>
                                        <xs:element name="url"/>
                                        <xs:element ref="description"/>
                                    </xs:sequence>
                                    <xs:attribute ref="id"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="regions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="region"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="keywords">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="keyword">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="title"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            ref="playerRefId"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sequences">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="sequence">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="playerRefId"/>
                                    </xs:sequence>
                                    <xs:attribute name="title"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="title"/>
    <xs:element name="description">
        <xs:complexType>
            <xs:group maxOccurs="unbounded" ref="block"/>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:element name="region">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="playerRefId" type="xs:IDREF"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="region"/>
            </xs:sequence>
            <xs:attribute ref="id"/>
        </xs:complexType>
    </xs:element>
    <xs:group name="block">
        <xs:choice>
            <xs:element ref="p"/>
            <xs:element ref="ul"/>
            <xs:element ref="ol"/>
            <xs:element ref="br"/>
            <xs:element ref="table"/>
            <xs:element name="media">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="title"/>
                        <xs:element minOccurs="0" name="caption">
                            <xs:complexType mixed="true">
                                <xs:group ref="inline"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute ref="id" use="required"/>
                    <xs:attribute name="url" type="xs:string" use="required"/>
                    <xs:attribute name="type" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:NMTOKEN">
                                <xs:enumeration value="imageWeb"/>
                                <xs:enumeration value="imageLocal"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="style" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element ref="editor"/>
        </xs:choice>
    </xs:group>
    <xs:element name="li">
        <xs:complexType mixed="true">
            <xs:group maxOccurs="unbounded" minOccurs="0" ref="inline"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="p">
        <xs:complexType mixed="true">
            <xs:group maxOccurs="unbounded" minOccurs="0" ref="inline"/>
        </xs:complexType>
    </xs:element>
    <xs:element fixed="" name="br" nillable="true"/>
    <xs:element name="hr"/>
    <xs:element name="ul">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="li"/>
                <xs:element minOccurs="0" ref="ul"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="ol">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element maxOccurs="unbounded" ref="li"/>
                <xs:element minOccurs="0" ref="ol"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element maxOccurs="unbounded" name="tr">
                    <xs:complexType mixed="false">
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="td">
                                <xs:complexType mixed="true">
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:group ref="block"/>
                                    </xs:choice>
                                    <xs:attribute name="style" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="style" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="border" type="xs:string" use="optional"/>
            <xs:attribute name="cellSpacing" type="xs:string" use="optional"/>
            <xs:attribute name="cellPadding" type="xs:string" use="optional"/>
            <xs:attribute name="style" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="editor">
        <xs:complexType mixed="true">
            <xs:attribute name="showEdits" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:group name="inline">
        <xs:choice>
            <xs:element minOccurs="0" ref="b"/>
            <xs:element minOccurs="0" ref="i"/>
            <xs:element minOccurs="0" ref="u"/>
            <xs:element minOccurs="0" ref="xref"/>
            <xs:element minOccurs="0" name="pubMentioned"/>
        </xs:choice>
    </xs:group>
    <xs:element name="i"/>
    <xs:element name="b"/>
    <xs:element name="u"/>
    <xs:element name="xref">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="xrefText">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="hotText"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="off"/>
                        <xs:enumeration value="web"/>
                        <xs:enumeration value="local"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="dest" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="playerRefId" type="xs:IDREF"/>
</xs:schema>

=== rajvseetharaman/Player_Base/XMLandXSD/playerBase.xml
<?xml version="1.0" encoding="UTF-8"?>
<cricketPlayerBase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="playerBase.xsd">
    <about>
        <title>Cricket Player Information System</title>
        <author>Rajendran Seetharaman</author>
        <description>
            <p>This is a <b>cricket player</b> info system which gives the following <i>information</i> about a cricket player
            </p>
            <ol>
                <li>The demographic information about the player like nationality, playing role, batting, and bowling styles</li>
                <li>The match statistics for the player like number of matches playes, runs scored, and wickets taken.</li>
            </ol>
            <p>My motive behind developing this system was that it could be used by avid cricket followers to look up information about their favorite player organized in a useful manner.</p>
        </description>
    </about>
    <cricketPlayers>
        <cricketPlayer id="p1">
            <title>Mahendra Singh Dhoni</title>
            <description>
                <p><u><b>India <i>Wicketkeeper batsman</i></b></u></p>
                <p><u>Career Highlights</u></p>
                <ul>
                    <li>MS Dhoni is arguably the most popular and definitely the most scrutinised cricketer from India.</li>
                    <li>Under Dhoni's captaincy, India have won the top prize in all formats.</li>
                    <li>India had the No.1 Test ranking in December 2009, the 50-over World Cup in 2011 and the <pubMentioned>World Twenty20</pubMentioned> on his captaincy debut in 2007</li>
                </ul>
                <br></br>
                <ol>
                    <li>ICC One-Day Player of the Year 2008</li>
                    <li>ICC One-Day Player of the Year 2009</li>
                    <li>ICC Spirit of Cricket Award 2011</li>
                    <li>LG People's Choice Award 2013</li>
                </ol>
                <br></br>
                <editor showEdits="true">ESPNCricInfo</editor>
            </description>
            <photos>
                <photo id="ph1" fileName="MSD.jpg" />
            </photos>
            <age>36</age>
            <gender>Male</gender>
            <nationalSide>India</nationalSide>
            <playingRole>Wicketkeeper batsman</playingRole>
            <battingStyle>Right Handed</battingStyle>
            <bowlingStyle>Right-arm medium</bowlingStyle>
            <gameStats>
                <matchesPlayed>1500</matchesPlayed>
                <inningsPlayed>2300</inningsPlayed>
                <battingAverages>
                    <runs>20000</runs>
                    <centuries>50</centuries>
                    <halfCenturies>150</halfCenturies>
                </battingAverages>
                <bowlingAverages>
                    <wickets>10</wickets>
                </bowlingAverages>
                <fieldingAverages>
                    <catches>1000</catches>
                </fieldingAverages>
            </gameStats>
            <sources>
                <sourceRefId>ESPN_IND</sourceRefId>
            </sources>
            <relatedPlayers>
                <playerRefId>p2</playerRefId>
                <playerRefId>p7</playerRefId>
            </relatedPlayers>
        </cricketPlayer>
        <cricketPlayer id="p2">
            <title>Ravichandran Ashwin</title>
            <description><p>India bowling allrounder</p></description>
            <photos>
                <photo id="ph2" fileName="RA.jpg" />
            </photos>
            <age>31</age>
            <gender>Male</gender>
            <nationalSide>India</nationalSide>
            <playingRole>Bowling allrounder</playingRole>
            <battingStyle>Right Handed</battingStyle>
            <bowlingStyle>Right-arm offbreak</bowlingStyle>
            <gameStats>
                <matchesPlayed>700</matchesPlayed>
                <inningsPlayed>1200</inningsPlayed>
                <battingAverages>
                    <runs>5000</runs>
                    <centuries>20</centuries>
                    <halfCenturies>50</halfCenturies>
                </battingAverages>
                <bowlingAverages>
                    <wickets>900</wickets>
                </bowlingAverages>
                <fieldingAverages>
                    <catches>300</catches>
                </fieldingAverages>
            </gameStats>
            <sources>
                <sourceRefId>ESPN_IND</sourceRefId>
            </sources>
            <relatedPlayers>
                <playerRefId>p3</playerRefId>
            </relatedPlayers>
        </cricketPlayer>
        <cricketPlayer id="p3">
            <title>Shikhar Dhawan</title>
            <description><p>India opening batsman</p></description>
            <photos>
                <photo id="ph3" fileName="SD.jpg" />
            </photos>
            <age>31</age>
            <gender>Male</gender>
            <nationalSide>India</nationalSide>
            <playingRole>Opening batsman</playingRole>
            <battingStyle>Left Handed</battingStyle>
            <bowlingStyle>Right-arm offbreak</bowlingStyle>
            <gameStats>
                <matchesPlayed>560</matchesPlayed>
                <inningsPlayed>900</inningsPlayed>
                <battingAverages>
                    <runs>15000</runs>
                    <centuries>200</centuries>
                    <halfCenturies>300</halfCenturies>
                </battingAverages>
                <bowlingAverages>
                    <wickets>15</wickets>
                </bowlingAverages>
                <fieldingAverages>
                    <catches>250</catches>
                </fieldingAverages>
            </gameStats>
            <sources>
                <sourceRefId>ESPN_IND</sourceRefId>
            </sources>
            <relatedPlayers>
                <playerRefId>p1</playerRefId>
            </relatedPlayers>
        </cricketPlayer>
        <cricketPlayer id="p4">
            <title>Kedar Mahadav Jadhav</title>
            <description><p>Indian batsman</p></description>
            <photos>
                <photo id="ph4" fileName="KMJ.jpg" />
            </photos>
            <age>32</age>
            <gender>Male</gender>
            <nationalSide>India</nationalSide>
            <playingRole>Batsman</playingRole>
            <battingStyle>Right Handed</battingStyle>
            <bowlingStyle>Right-arm offbreak</bowlingStyle>
            <gameStats>
                <matchesPlayed>200</matchesPlayed>
                <inningsPlayed>300</inningsPlayed>
                <battingAverages>
                    <runs>6000</runs>
                    <centuries>45</centuries>
                    <halfCenturies>60</halfCenturies>
                </battingAverages>
                <bowlingAverages>
                    <wickets>15</wickets>
                </bowlingAverages>
                <fieldingAverages>
                    <catches>200</catches>
                </fieldingAverages>
            </gameStats>
            <sources>
                <sourceRefId>ESPN_IND</sourceRefId>
            </sources>
            <relatedPlayers>
                <playerRefId>p3</playerRefId>
            </relatedPlayers>
        </cricketPlayer>
        <cricketPlayer id="p5">
            <title>Kuldeep Yadav</title>
            <description><p>Indian bowler</p></description>
            <photos>
                <photo id="ph5" fileName="KY.jpg" />
            </photos>
            <age>22</age>
            <gender>Male</gender>
            <nationalSide>India</nationalSide>
            <playingRole>Bowler</playingRole>
            <battingStyle>Left Handed</battingStyle>
            <bowlingStyle>Slow left-arm chinaman</bowlingStyle>
            <gameStats>
                <matchesPlayed>150</matchesPlayed>
                <inningsPlayed>200</inningsPlayed>
                <battingAverages>
                    <runs>4000</runs>
                    <centuries>40</centuries>
                    <halfCenturies>55</halfCenturies>
                </battingAverages>
                <bowlingAverages>
                    <wickets>45</wickets>
                </bowlingAverages>
                <fieldingAverages>
                    <catches>150</catches>
                </fieldingAverages>
            </gameStats>
            <sources>
                <sourceRefId>ESPN_IND</sourceRefId>
            </sources>
            <relatedPlayers>
                <playerRefId>p3</playerRefId>
            </relatedPlayers>
        </cricketPlayer>
        <cricketPlayer id="p6">
            <title>Jasprit Jasbirsingh Bumrah</title>
            <description><p>Indian bowler</p></description>
            <photos>
                <photo id="ph6" fileName="JJB.jpg" />
            </photos>
            <age>22</age>
            <gender>Male</gender>
            <nationalSide>India</nationalSide>
            <playingRole>Bowler</playingRole>
            <battingStyle>Right Handed</battingStyle>
            <bowlingStyle>Right-arm medium</bowlingStyle>
            <gameStats>
                <matchesPlayed>200</matchesPlayed>
                <inningsPlayed>250</inningsPlayed>
                <battingAverages>
                    <runs>5000</runs>
                    <centuries>45</centuries>
                    <halfCenturies>55</halfCenturies>
                </battingAverages>
                <bowlingAverages>
                    <wickets>60</wickets>
                </bowlingAverages>
                <fieldingAverages>
                    <catches>170</catches>
                </fieldingAverages>
            </gameStats>
            <sources>
                <sourceRefId>ESPN_IND</sourceRefId>
            </sources>
            <relatedPlayers>
                <playerRefId>p4</playerRefId>
            </relatedPlayers>
        </cricketPlayer>
        <cricketPlayer id="p7">
